spring:
  application:
    name: instance-service
  config:
    import:
      - optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}

  profiles:
    group:
      setup-local:
        - setup
        - local
      setup-docker:
        - setup
        - docker

  cloud:
    config:
      fail-fast: true
      retry:
        max-attempts: 3
        initial-interval: 1000
        multiplier: 1.5
        max-interval: 5000
