app:
  name: ${APP_NAME:syncturtle}
  edition: ${APP_EDITION:COMMUNITY}
  test: ${APP_TEST:false}
  telemetry:
    enabled: ${APP_TELEMETRY_ENABLED:true}
    support-required: ${APP_TELEMETRY_SUPPORT_REQUIRED:false}
  skip-env-var: ${APP_SKIP_ENV_VAR:false}
  web-url: ${APP_WEB_URL:http://localhost:3000}
  base-urls:
    admin: ${APP_BASE_URL_ADMIN:http://localhost:3001/god-mode/}
    app: ${APP_BASE_URL_APP:http://localhost:3000/}
  config-keys:
    enable-signup: ${APP_ENABLE_SIGNUP:1}
    enable-email-password: ${APP_ENABLE_EMAIL_PASSWORD:1}
    disable-workspace-creation: ${APP_DISABLE_WORKSPACE_CREATION:0}

    enable-smtp: ${APP_ENABLE_SMTP:0}
    email-host: ${APP_EMAIL_HOST:}
    email-host-user: ${APP_EMAIL_HOST_USER:}
    email-host-password: ${APP_EMAIL_HOST_PASSWORD:}
    email-port: ${APP_EMAIL_PORT:587}
    email-from: ${APP_EMAIL_FROM:}
    email-use-tls: ${APP_EMAIL_USE_TLS:1}
    email-use-ssl: ${APP_EMAIL_USE_SSL:0}

    enable-magic-link-login: ${APP_ENABLE_MAGIC_LINK_LOGIN:0}

    google-client-id: ${APP_GOOGLE_CLIENT_ID:}
    google-client-secret: ${APP_GOOGLE_CLIENT_SECRET:}

    github-client-id: ${APP_GITHUB_CLIENT_ID:}
    github-client-secret: ${APP_GITHUB_CLIENT_SECRET:}

    gitlab-host: ${APP_GITLAB_HOST:}
    gitlab-client-id: ${APP_GITLAB_CLIENT_ID:}
    gitlab-client-secret: ${APP_GITLAB_CLIENT_SECRET:}

    intercom-app-id: ${APP_INTERCOM_APP_ID:}

    posthog-api-key: ${APP_POSTHOG_API_KEY:}
    posthog-host: ${APP_POSTHOG_HOST:}
  security:
    encryption:
      secret-key: ${APP_SECURITY_ENCRYPTION_SECRET_KEY}
  kafka:
    enabled: true
  product-telemetry:
    enabled: true
    endpoint: ${PRODUCT_TELEMETRY_ENDPOINT:http://localhost:15317}
    api-key: ""
    interval: 10m
  response-cache:
    enabled: true
    key-prefix: "st:resp:"
    hash-bytes: 16

server:
  port: 8001

spring:
  application:
    name: instance-service

  datasource:
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-timeout: 2000

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:19092}
    template:
      observation-enabled: true
    listener:
      observation-enabled: true
      auto-startup: ${app.kafka.enabled:true}
    producer:
      acks: all
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        enable.idempotence: true
        linger.ms: 5
        batch.size: 32768
        compression.type: zstd
        max.in.flight.requests.per.connection: 5
        spring.json.add.type.headers: false # JsonSerializer.ADD_TYPE_INFO_HEADERS
        interceptor.classes: com.syncturtle.common.spring.kafka.MdcKafkaHeaderProducerInterceptor
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "com.syncturtle.*"
        spring.json.use.type.headers: false

jdbc:
  datasource-proxy:
    enabled: true
    include-parameter-values: false
  includes: QUERY
