eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/syncturtle_instance
    username: instance_svc
    password: ${INSTANCE_DB_PASSWORD:instance_svc_dev}
