server:
  port: 8002

spring:
  application:
    name: user-service

  datasource:
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-timeout: 2000

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:19092}
    template:
      observation-enabled: true
    listener:
      observation-enabled: true
      auto-startup: ${app.kafka.enabled:true}
    producer:
      acks: all
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        enable.idempotence: true
        linger.ms: 5
        batch.size: 32768
        compression.type: zstd
        max.in.flight.requests.per.connection: 5
        spring.json.add.type.headers: false # JsonSerializer.ADD_TYPE_INFO_HEADERS
        interceptor.classes: com.syncturtle.common.spring.kafka.MdcKafkaHeaderProducerInterceptor
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.json.value.default.type: com.syncturtle.common.core.events.UserEvent
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "com.syncturtle.*"
        spring.json.use.type.headers: false

jdbc:
  datasource-proxy:
    enabled: true
    include-parameter-values: false
  includes: QUERY
