eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/syncturtle_user
    username: user_svc
    password: ${USER_DB_PASSWORD:user_svc_dev}

  liquibase:
    default-schema: user
    liquibase-schema: user_liquibase
