nodeLinker: node-modules
nmMode: hardlinks-local

catalog:
  typescript: 5.9.3
  eslint: 9.39.4
  prettier: 3.8.1
  prettier-plugin-tailwindcss: 0.7.2
  turbo: 2.9.1
  tsup: 8.5.1
  vite: 7.3.0

  "@eslint/js": 9.39.4
  eslint-config-prettier: 10.1.8
  typescript-eslint: 8.50.0

  lodash: 4.18.1
  "@types/lodash": 4.17.24

  clsx: 2.1.1
  tailwind-merge: 3.5.0
  tailwindcss: 4.2.2
  "@tailwindcss/postcss": 4.2.2

  lucide-react: 0.562.0
  next-themes: 0.4.6
  swr: 2.4.1
  zod: 4.3.6
  intl-messageformat: 11.2.0

  "@t3-oss/env-nextjs": 0.13.11
  file-type: 22.0.1
  react-dropzone: 15.0.0
  string-ts: 2.3.1
  ufo: 1.6.3

  "@yarnpkg/types": 4.0.0

catalogs:
  react19:
    react: 19.2.4
    react-dom: 19.2.4
    "@types/react": 19.2.14
    "@types/react-dom": 19.2.3

  next16:
    next: 16.2.9
    eslint-config-next: 16.2.1
    "@types/node": 25.5.0

  heroui3:
    "@heroui/react": 3.2.1
    "@heroui/styles": 3.2.1

  storybook10:
    storybook: 10.3.5
    "@storybook/addon-docs": 10.3.5
    "@storybook/react-vite": 10.3.5
