--liquibase formatted sql

--changeset syncturtle:0001-006-seed-system-user labels:user
INSERT INTO users (
    created_at,
    updated_at,
    id,
    username,
    mobile_number,
    email,
    display_name,
    first_name,
    last_name,
    password_hash,
    avatar_asset_id,
    cover_image_asset_id,
    is_managed,
    is_password_expired,
    is_active,
    is_email_verified,
    is_password_autoset,
    is_email_valid,
    user_timezone,
    last_active,
    last_login_time,
    last_login_ip,
    last_login_medium,
    last_login_uagent,
    principal_type,
    masked_at,
    auth_version,
    version,
    created_by_id,
    updated_by_id
)
VALUES (
    now(),
    now(),
    '00000000-0000-0000-0000-000000000001',
    'system',
    NULL,
    'system@syncturtle.internal',
    'Syncturtle System',
    '',
    '',
    NULL,
    NULL,
    NULL,
    TRUE,
    FALSE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    'UTC',
    now(),
    NULL,
    '',
    'system',
    '',
    'SYSTEM',
    NULL,
    1,
    1,
    '00000000-0000-0000-0000-000000000001',
    '00000000-0000-0000-0000-000000000001'
)
ON CONFLICT (id) DO UPDATE
SET
    updated_at = now(),
    username = EXCLUDED.username,
    email = EXCLUDED.email,
    display_name = EXCLUDED.display_name,
    principal_type = EXCLUDED.principal_type,
    is_managed = EXCLUDED.is_managed,
    is_active = EXCLUDED.is_active,
    is_email_verified = EXCLUDED.is_email_verified,
    is_password_autoset = EXCLUDED.is_password_autoset,
    is_email_valid = EXCLUDED.is_email_valid,
    user_timezone = EXCLUDED.user_timezone,
    updated_by_id = EXCLUDED.updated_by_id;

--rollback DELETE FROM users WHERE id = '00000000-0000-0000-0000-000000000001';