eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    hostname: localhost
    instance-id: ${spring.application.name}:${server.port}

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/syncturtle_instance
    username: instance_svc
    password: ${INSTANCE_DB_PASSWORD:instance_svc_dev}
