management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics
          - env
          - configprops

  tracing:
    sampling:
      probability: 1.0

  opentelemetry:
    tracing:
      export:
        schedule-delay: 1s

        otlp:
          endpoint: ${OTLP_TRACES_ENDPOINT:http://localhost:14317}
          transport: grpc

    logging:
      export:
        schedule-delay: 1s

        otlp:
          endpoint: ${OTLP_LOGS_ENDPOINT:http://localhost:14317}
          transport: grpc

  otlp:
    metrics:
      export:
        url: ${OTLP_METRICS_URL:http://localhost:14318/v1/metrics}
        step: 10s

app:
  gateway:
    client-metadata:
      trusted-proxy-count: ${GATEWAY_TRUSTED_PROXY_COUNT:0}
