management:
  endpoints:
    web:
      exposure:
        include:
        - health
        - info
        - metrics
        - env
        - configprops
  tracing:
    sampling:
      probability: 1.0