spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/syncturtle_email
    username: email_app
    password: ${EMAIL_DB_PASSWORD}

  liquibase:
    user: email_migrator
    password: ${EMAIL_MIGRATOR_DB_PASSWORD}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:19092}

app:
  clients:
    instance-service:
      base-url: http://localhost:8001
      connect-timeout: 2s
      read-timeout: 5s
