spring:
  application:
    name: user-service
  jpa:
    properties:
      hibernate:
        type:
          json_format_mapper: jackson3
  config:
    import:
      - optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}
  
  cloud:
    config:
      fail-fast: true
      retry:
        max-attempts: 3
        initial-interval: 1000
        multiplier: 1.5
        max-interval: 5000
